sudo: false
language: php

notifications:
  email: false

php:
  - "7.0"
  - "7.1"
  - "7.2"

env:
  global:
    - TEST_PHP_ARGS="-q"
    - REPORT_EXIT_STATUS=1

script:
  - cd extension
  - phpize
  - ./configure
  - make
  - make install
  - make -f Makefile.local test_with_exit_status

after_failure: "tail -vn+1 tests/*.diff"
